# Generated by Django 4.0.2 on 2022-03-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ton', models.CharField(max_length=10)),
                ('Gram', models.CharField(max_length=10)),
                ('Troy_ounce', models.CharField(max_length=10)),
                ('Kilogram', models.CharField(max_length=10)),
                ('Pound', models.CharField(max_length=10)),
                ('Ounce', models.CharField(max_length=10)),
            ],
        ),
    ]
