# Generated by Django 4.0.2 on 2022-03-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0002_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversiontable',
            name='Gram',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conversiontable',
            name='Kilogram',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conversiontable',
            name='Ounce',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conversiontable',
            name='Pound',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conversiontable',
            name='Ton',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conversiontable',
            name='Troy_ounce',
            field=models.FloatField(),
        ),
    ]
